name: Build Container

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9

jobs:
      build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
            - name: 'Checkout GitHub Action'
              uses: actions/checkout@main

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version:  ${{ env.PYTHON_VERSION }}

            - name: Install Poetry
              uses: Gr1N/setup-poetry@v8

            - name: Install dependencies
              run: poetry install

            - name: Run container build
              run: poetry run ansible-builder build --tag ghcr.io/jamesholland-uk/ansible-ee:latest
