name: Build and Publish Container

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9

jobs:
      build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
            - name: Checkout GitHub Action
              uses: actions/checkout@main

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version:  ${{ env.PYTHON_VERSION }}

            - name: Install Poetry
              uses: Gr1N/setup-poetry@v8

            - name: Install dependencies
              run: poetry install

            - name: Run container build
              run: poetry run ansible-builder build --tag ghcr.io/jamesholland-uk/ansible-ee:latest

      #       - name: Store built container
      #         uses: actions/upload-artifact@v3
      #         with:
      #           path: './'

      # push-store-image:
      #   runs-on: ubuntu-latest
      #   needs: build
      #   defaults:
      #     run:
      #       working-directory: './'
      #   steps:
      #       - name: Checkout GitHub Action
      #         uses: actions/checkout@main
    
            # - name: Login to GitHub Container Registry
            #   uses: docker/login-action@v2
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: redhat-actions/podman-login@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Inventory Image
              run: |
                pwd
                docker images
                podman images
                podman push ghcr.io/jamesholland-uk/ansible-ee:latest
